export const galleryItems = [
    {
        id: 1,
        title: "Забор из евроштакетника",
        images: [
            "/assets/img/gallery/gallery1.webp",
            "/assets/img/gallery/gallery2.webp",
            "/assets/img/gallery/gallery3.webp",
            "/assets/img/gallery/gallery4.webp",
            "/assets/img/gallery/gallery5.webp",
        ],
        tag: "евроштакетник",
        year: "2024",
        width: "Общая длинна - 100 м",
        height: "Высота забора - 2 м",
    },
    {
        id: 2,
        title: "Забор из евроштакетника",
        images: [
            "/assets/img/gallery/gallery1.webp",
            "/assets/img/gallery/gallery2.webp",
            "/assets/img/gallery/gallery3.webp",
            "/assets/img/gallery/gallery4.webp",
            "/assets/img/gallery/gallery5.webp",
        ],
        tag: "евроштакетник",
        year: "2024",
        width: "Общая длинна - 100 м",
        height: "Высота забора - 2 м",
    },
    {
        id: 3,
        title: "Забор из евроштакетника",
        images: [
            "/assets/img/gallery/gallery1.webp",
            "/assets/img/gallery/gallery2.webp",
            "/assets/img/gallery/gallery3.webp",
            "/assets/img/gallery/gallery4.webp",
            "/assets/img/gallery/gallery5.webp",
        ],
        tag: "евроштакетник",
        year: "2024",
        width: "Общая длинна - 100 м",
        height: "Высота забора - 2 м",
    },
    {
        id: 4,
        title: "Забор из евроштакетника",
        images: [
            "/assets/img/gallery/gallery1.webp",
            "/assets/img/gallery/gallery2.webp",
            "/assets/img/gallery/gallery3.webp",
            "/assets/img/gallery/gallery4.webp",
            "/assets/img/gallery/gallery5.webp",
        ],
        tag: "евроштакетник",
        year: "2024",
        width: "Общая длинна - 100 м",
        height: "Высота забора - 2 м",
    },
];
