export const servicesItems = [
    {
        id: 1,
        title: "заборы из профлиста",
        price: "от 3500 руб. пог/м. под ключ",
        img: "/assets/img/sections/services1.webp",
        link: "",
    },
    {
        id: 2,
        title: "Заборы из евроштакетника",
        price: "от 2500 руб. пог/м. под ключ",
        img: "/assets/img/sections/services2.webp",
        link: "",
    },
    {
        id: 3,
        title: "заборы 3д-гардис",
        price: "от 2000 руб. пог/м. под ключ",
        img: "/assets/img/sections/services3.webp",
        link: "",
    },
    {
        id: 4,
        title: "Заборы из дерева",
        price: "от 3400 руб. пог/м. под ключ",
        img: "/assets/img/sections/services4.webp",
        link: "",
    },
    {
        id: 5,
        title: "Каркас забора",
        price: "от 2000 руб. пог/м. под ключ",
        img: "/assets/img/sections/services5.webp",
        link: "",
    },
    {
        id: 6,
        title: "ЗАБОРЫ ЖАЛЮЗИ",
        price: "от 6200 руб. пог/м. под ключ",
        img: "/assets/img/sections/services6.webp",
        link: "",
    },
    {
        id: 7,
        title: "Заборы из сетки рабицы",
        price: "от 1950 руб. пог/м. под ключ",
        img: "/assets/img/sections/services7.webp",
        link: "",
    },
    {
        id: 8,
        title: "Металлические заборы",
        price: "от 4500 руб. пог/м. под ключ",
        img: "/assets/img/sections/services8.webp",
        link: "",
    },
];
